gcloud compute instances create controller-1 --async --project=thwthw --zone=asia-southeast1-a --machine-type=e2-standard-2 --subnet=kubernetes --can-ip-forward --private-network-ip "10.240.0.11" --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=73201300452-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=kubernetes-the-hard-way,controller --create-disk=auto-delete=yes,boot=yes,device-name=controller-1,image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230919,mode=rw,size=80,type=projects/thwthw/zones/asia-southeast1-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any

gcloud compute instances create controller-2 --async --project=thwthw --zone=asia-southeast1-b --machine-type=e2-standard-2 --subnet=kubernetes --can-ip-forward --private-network-ip "10.240.0.12" --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=73201300452-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=kubernetes-the-hard-way,controller --create-disk=auto-delete=yes,boot=yes,device-name=controller-2,image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230919,mode=rw,size=80,type=projects/thwthw/zones/asia-southeast1-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any

gcloud compute instances create controller-3 --async --project=thwthw --zone=asia-southeast1-c --machine-type=e2-standard-2 --subnet=kubernetes --can-ip-forward --private-network-ip "10.240.0.13" --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=73201300452-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=kubernetes-the-hard-way,controller --create-disk=auto-delete=yes,boot=yes,device-name=controller-3,image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230919,mode=rw,size=80,type=projects/thwthw/zones/asia-southeast1-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any





gcloud compute instances create worker-1 --project=thwthw --zone=asia-southeast1-a --machine-type=e2-standard-2 --subnet=kubernetes --can-ip-forward --private-network-ip "10.240.0.21" --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=73201300452-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=kubernetes-the-hard-way,worker --create-disk=auto-delete=yes,boot=yes,device-name=worker-1,image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230919,mode=rw,size=80,type=projects/thwthw/zones/asia-southeast1-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any

gcloud compute instances create worker-2 --async --project=thwthw --zone=asia-southeast1-b --machine-type=e2-standard-2 --subnet=kubernetes --can-ip-forward --private-network-ip "10.240.0.22" --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=73201300452-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=kubernetes-the-hard-way,worker --create-disk=auto-delete=yes,boot=yes,device-name=worker-2,image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230919,mode=rw,size=80,type=projects/thwthw/zones/asia-southeast1-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any

gcloud compute instances create worker-3 --async --project=thwthw --zone=asia-southeast1-c --machine-type=e2-standard-2 --subnet=kubernetes --can-ip-forward --private-network-ip "10.240.0.23" --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=73201300452-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=kubernetes-the-hard-way,worker --create-disk=auto-delete=yes,boot=yes,device-name=worker-3,image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230919,mode=rw,size=80,type=projects/thwthw/zones/asia-southeast1-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any

